#cloud-config

groups:
  - docker

system_info:
  default_user:
    groups: [docker]

users:
  - default
  - name: MYUSERNAME
    groups: sudo, docker
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    shell: /bin/bash
    ssh_authorized_keys:
      - ssh-rsa MYPUBLICKEY 

timezone: US/Eastern

apt:
  sources:
    docker.list:
      source: deb [arch=amd64] https://download.docker.com/linux/ubuntu $RELEASE stable
      keyid: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88

package_update: true
package_upgrade: true
packages:
  - apt-transport-https
  - ca-certificates
  - gnupg-agent
  - software-properties-common
  - curl
  - git
  - fail2ban
  - docker-ce
  - docker-ce-cli
  - containerd.io
    
write_files:
  - path: /etc/sysctl.d/enabled.conf
    content: |
      net.ipv4.conf.all.forwarding=1
      net.bridge.bridge-nf-call-iptables=1

runcmd:
  - swapoff -a
  #firewall rules are handled by openstack
  - ufw allow 1:32767/tcp
  - ufw allow 1:32767/udp
  - systemctl enable ufw
  #fail2ban
  - printf "[sshd]\nenabled = true\nbanaction = iptables-multiport" > /etc/fail2ban/jail.local
  - systemctl enable fail2ban
  #ssh
  - sed -i -e '/^\(#\|\)PermitRootLogin/s/^.*$/PermitRootLogin no/' /etc/ssh/sshd_config
  - sed -i -e '/^\(#\|\)PasswordAuthentication/s/^.*$/PasswordAuthentication no/' /etc/ssh/sshd_config
  - sed -i '$a AllowUsers MYUSERNAME' /etc/ssh/sshd_config
  - systemctl restart ssh
